"""Abandoned-cart email reminder.

Caveat (see CLAUDE.md > Architecture): this app has no database and no
background job scheduler, by deliberate design (free single-service
hosting on Streamlit Community Cloud). This reminder can therefore only
fire while the customer's browser tab stays open on the page — see
streamlit_app/Home.py, which polls elapsed time via a lightweight
auto-refresh and calls `AbandonedCartReminderTool.send` once the
threshold is crossed. It cannot notify a customer who has closed the
tab; a true "always fires later" reminder would require persisting cart
state and a server-side scheduler, which is out of scope for this
architecture.
"""

import structlog

from app.agent.state import CustomerDetails
from app.agent.tools.cart_tool import CartLine, format_cart
from app.services.email_service import EmailService
from app.store.models import BusinessConfig

logger = structlog.get_logger(__name__)


def build_abandoned_cart_email(
    cart: list[CartLine],
    customer_details: CustomerDetails,
    business_config: BusinessConfig,
) -> tuple[str, str]:
    """Pure function — like reply_templates.py and
    order_confirmation_tool.py, this content is built entirely from
    known state, never generated by an LLM.
    """
    subject = f"You left items in your cart at {business_config.business_name}"

    name = customer_details.get("name")
    greeting = f"Hi {name}," if name else "Hi,"

    body = (
        f"{greeting}\n\n"
        "You still have items waiting in your cart:\n\n"
        f"{format_cart(cart, business_config)}\n\n"
        f"Call us at {business_config.payment_phone_number} to complete "
        "your order.\n"
    )
    return subject, body


class AbandonedCartReminderTool:
    """Agent tool: emails the customer once, reminding them about items
    left in their cart. Only sends when a customer email is known.
    """

    def __init__(self, email_service: EmailService) -> None:
        self._email_service = email_service

    async def send(
        self,
        cart: list[CartLine],
        customer_details: CustomerDetails,
        business_config: BusinessConfig,
    ) -> bool:
        customer_email = customer_details.get("email")
        if not customer_email or not cart:
            return False

        subject, body = build_abandoned_cart_email(cart, customer_details, business_config)
        try:
            await self._email_service.send(customer_email, subject, body)
        except Exception:
            logger.error("abandoned_cart_email_failed", to=customer_email)
            return False
        return True
