import structlog

from app.agent.state import CustomerDetails
from app.agent.tools.cart_tool import CartLine, format_cart
from app.services.email_service import EmailService
from app.store.models import BusinessConfig

logger = structlog.get_logger(__name__)


def build_order_summary_email(
    order_id: str,
    cart: list[CartLine],
    customer_details: CustomerDetails,
    delivery_slot: str | None,
    business_config: BusinessConfig,
) -> tuple[str, str]:
    """Builds (subject, body) for the order confirmation email. Pure
    function, no I/O — built entirely from already-known order state,
    same discipline as app/agent/reply_templates.py: the email content
    is never generated by an LLM.
    """
    subject = f"{business_config.business_name} — Order Confirmation {order_id}"

    lines = [
        f"Order ID: {order_id}",
        "",
        "Customer Details",
        f"Name: {customer_details.get('name', '')}",
        f"Phone: {customer_details.get('phone', '')}",
        f"Email: {customer_details.get('email', '')}",
        f"Address: {customer_details.get('address', '')}",
    ]
    maps_link = customer_details.get("maps_link")
    if maps_link:
        lines.append(f"Maps Link: {maps_link}")

    lines += [
        "",
        "Order",
        format_cart(cart, business_config),
        "",
        f"Delivery Slot: {delivery_slot or 'Not specified'}",
        "Payment Status: Paid (advance payment validated)",
    ]

    return subject, "\n".join(lines)


class OrderConfirmationTool:
    """Agent tool: emails the order confirmation to the admin inbox and
    the customer after payment validation succeeds. There is no
    database — this email is the durable order record (see
    CLAUDE.md > Architecture). Email failure is logged and retried
    (EmailService already retries 3x) but never blocks confirming the
    order to the customer in-chat — payment already succeeded, so the
    order is valid regardless of whether the notification email lands.
    """

    def __init__(self, email_service: EmailService, admin_email: str) -> None:
        self._email_service = email_service
        self._admin_email = admin_email

    async def send(
        self,
        order_id: str,
        cart: list[CartLine],
        customer_details: CustomerDetails,
        delivery_slot: str | None,
        business_config: BusinessConfig,
    ) -> None:
        subject, body = build_order_summary_email(
            order_id, cart, customer_details, delivery_slot, business_config
        )

        recipients = [self._admin_email]
        customer_email = customer_details.get("email")
        if customer_email:
            recipients.append(customer_email)

        for recipient in recipients:
            try:
                await self._email_service.send(recipient, subject, body)
            except Exception:
                logger.error("order_confirmation_email_failed", order_id=order_id, to=recipient)
